### ISSUE TITLE
False positives: kobo.com and koyu.space

### ISSUE THREAD

**Issue by austinhuang0131** [MDP43140/BaDomain#1]
kobo.com is a large eBooks store.

koyu.space is a Mastodon (selfhosted social media) instance.

**Comment by MDP43140** [comment]
Thanks for reminding this, i cant open kobo.com in tor browser so i dont know what is this and just blocked it, i tried opening the website in firefox, now it shows as eBook and audiobook, while koyu.space i blocked it without checking the website in tor first (because the .space domain looks sus). it should be fixed now.
