### ISSUE TITLE
List for block Brawl Stars

### ISSUE THREAD

**Issue by EdyStauch** [MDP43140/BaDomain#3]
Could you generate a list to block the Brawl Stars game? Thank you very much.

**Comment by MDP43140** [comment]
Honestly i don't play Brawl Stars, so i don't know what DNS requests does the game mainly connects to, but what i know is the game is developed by Supercell (their domain is supercell[.]com), i can query and block most of the subdomains.

You can use something like Adaway or Blokada to log the game request.
Let me know if you found more Supercell subdomains that i can add to the blocklist.

(btw i added Supercell domains to the main blocklist because when i searched the company name, it shows up that it has been bought by Tencent (https://en.wikipedia.org/wiki/Supercell_(video_game_company)), which is a Chinese company and you know i don't like chinese companies collecting data about us).

Fixed with #de2241d commit.
